### PR TITLE
Updated licenses and documentation, increased versatility of copyright parser, and other small changes.

### PR DESCRIPTION
**Pull request by mkrupcale**
* Increased version to 1.5.0
* all text files: Converted line endings to UNIX format
* all java source files: Fixed formatting to be more consistent with 2-space indentation
* .gitignore: Exclude compiled `bin/` files
* com.wdev91.eclipse.copyright.feature/feature.xml: Bump minor version
* com.wdev91.eclipse.copyright.feature/feature.xml: Add version requirements to dependencies (from com.wdev91.eclipse.copyright/META-INF/MANIFEST.MF)
* com.wdev91.eclipse.copyright.feature/feature.xml: Add feature dependency on org.eclipse.help (moved from plugin dependency since it is optional)
* com.wdev91.eclipse.copyright/META-INF/MANIFEST.MF: Bump minor version
* com.wdev91.eclipse.copyright/META-INF/MANIFEST.MF: Remove org.eclipse.help from plugin dependencies, since it is unused by plugin
* com.wdev91.eclipse.copyright/epl-v10.html: Downloaded updated copy from website (minor formatting changes)
* com.wdev91.eclipse.copyright/help/prefs_copyright.html: Minor grammar fixes
* com.wdev91.eclipse.copyright/help/prefs_copyright.html: Update to reflect added licenses
* com.wdev91.eclipse.copyright/help/prefs_formats.html: Minor grammar fixes
* com.wdev91.eclipse.copyright/help/prefs_formats.html: Update to reflected added content types for file headers
* com.wdev91.eclipse.copyright/help/prefs_project.html: Minor grammar fixes
* com.wdev91.eclipse.copyright/src/com/wdev91/eclipse/copyright/model/CopyrightManager.java: Rename `firstInstructionFinded` to more grammatically correct `firstInstructionFound`
* com.wdev91.eclipse.copyright/src/com/wdev91/eclipse/copyright/model/CopyrightManager.java: Added `getCdataTextContent()` method to concatenate text content of CDATA_SECTION child nodes for given parent node. This allows for possibility of: 1) child text (i.e. whitespace) nodes for nicer XML formatting; 2) although unlikely, CDATA sections cannot contain `]]>`, so one must use multiple consecutive CDATA sections, splitting this triad, as in `<![CDATA[]]]]><![CDATA[>]]>`.
* com.wdev91.eclipse.copyright/src/com/wdev91/eclipse/copyright/model/CopyrightManager.java: Add 'C Source File', 'C Header File', 'C++ Source File', and 'C++ Header File' content types to available header formats if available
* com.wdev91.eclipse.copyright/src/com/wdev91/eclipse/copyright/model/CopyrightManager.java: Use `getCdataTextContent()` method in `loadHeadersFormats()` when parsing header XML file and in `readCopyrights()` when parsing copyrights XML file
* com.wdev91.eclipse.copyright/src/com/wdev91/eclipse/copyright/model/HeaderFormat.java: Add 'C Source File', 'C Header File', 'C++ Source File', and 'C++ Header File' content types to `HeaderFormat` with default C/C++-style comment formats
* com.wdev91.eclipse.copyright/src/copyrights.xml: Renamed license filename for GPLv2+, GPLv3+, and LGPLv2.1+ licenses from `license.txt` to `COPYING` to be more consistent with GNU convention
* com.wdev91.eclipse.copyright/src/copyrights.xml: Added text versions of files for Apache License version 2.0 and Eclipse Public License (EPL) version 1.0
* com.wdev91.eclipse.copyright/src/copyrights.xml: Added headers and licenses for Boost Software License (BSL) version 1.0; 2-, 3-, and 4-clause BSD licenses; GNU Affero General Public License (AGPL) version 3+; GNU Lesser General Public License (LGPL) version 3+; ISC License; MIT (Expat) License; Mozilla Public Licence (MPL) version 2.0

### CODE REVIEW

**Comment by jmini** [comment]
I had a quick look and it looks fine for me.
**Thank you a lot** for this work and for the contribution to this repository.

For your information: I will try to publish the plugin (your updated version) on a p2 update site on Bintray.

**Comment by mkrupcale** [comment]
Glad I could make improvements to this plugin. That sounds like a good idea publishing it there.

**Comment by jmini** [comment]
Have a look at the new project page: https://jmini.github.io/Eclipse-Copyright-Generator/
You will find the link to the P2 Update Site.

**Comment by mkrupcale** [comment]
Awesome it looks good. Having the P2 Update Site is especially useful I think because it will lower the barrier for newcomers to use this plugin. I had actually never worked with Eclipse plugins before and so I had to compile and install it manually.

**Pull request merged**
